version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: DB/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1977
      POSTGRES_DB: vk
    volumes:
      - db_data:/var/lib/postgresql/data

  pinger:
    build:
      context: .
      dockerfile: Pinger/Dockerfile
    depends_on:
      - kafka
      - backend
    restart: on-failure

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    depends_on:
      - db
      - kafka
    restart: on-failure

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Указываем подключение к ZooKeeper
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092 # Указываем подключение к ZooKeeper
    depends_on:
      - zookeeper


  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: on-failure

volumes:
  db_data: